### PR TITLE
- fix MinGW build

### PR DESCRIPTION
**Pull request by SSE4**
https://github.com/bincrafters/community/issues/4

/cc @dimi309

### CODE REVIEW

**Comment by dimi309** [comment]
The change is on line 189 of the committed modification to conanfile.py and I have just ascertained that it works! Thanks @SSE4 !

**Comment by dimi309** [comment]
They're sort of improvements and he already solved the problem... I'm just sayin' ... Sorry if I talk too much guys...

**Comment by dimi309** [comment]
I usually lean on the "let things pass" side, maybe a bit too much sometimes. I can see that technically, you are right.

**Comment by SSE4** [comment]
@grafikrobot rebased into two commits

**Pull request merged**
